function structures = changeStructuresName(structures)

for i = 1:length(structures)
    structureName = structures(i).structureName;
    if ~isempty(strfind(structureName,'gtv')) || ...
            ~isempty(strfind(structureName,'GTV')) || ...
            ~isempty(strfind(structureName,'PV')) || ...
            ~isempty(strfind(structureName,'Avoidance')) || ...
            ~isempty(strfind(structureName,'-')) || ...
            ~isempty(strfind(structureName,'_')) || ...
            ~isempty(strfind(structureName,'N3')) || ...
            (i>=2 && strcmp(structureName,structures(i-1).structureName))
        structures(i).structureName = 'OUT';
    else
        structures(i).structureName =strrep(structureName,' ','_');
    end
end
